name: therapy_user
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_storage: ^2.1.1
  get: any
  table_calendar: any
  flutter_dotenv: ^5.1.0
  iconly:
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.2
  readmore: ^2.2.0
  badges: ^3.1.2
  upgrader: ^8.1.0
  auto_size_text: ^3.0.0
  google_fonts: ^6.1.0
  expandable_text: ^2.3.0
  image_picker: 
  file_picker: 
  images_picker:
  timeago: ^3.5.0
  font_awesome_flutter: ^10.6.0
  syncfusion_flutter_pdfviewer:
  firebase_messaging: ^14.7.6
  firebase_core: ^2.24.0
  flutter_local_notifications: ^16.2.0
  courier_flutter: ^2.0.1
  onesignal_flutter: ^5.0.4
  flutter_file_downloader: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env  
